"""updated user column

Revision ID: 117adc1f6eb3
Revises: 2148bcf8bff1
Create Date: 2023-06-24 16:53:07.513118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117adc1f6eb3'
down_revision = '2148bcf8bff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
