"""create categories table

Revision ID: dda2ba748723
Revises: 87a6708e14c4
Create Date: 2022-08-15 01:23:03.883539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda2ba748723'
down_revision = '87a6708e14c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
