"""Update Project Table

Revision ID: 34da452ba339
Revises: 1d18bf24593f
Create Date: 2023-02-03 01:41:47.271873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34da452ba339'
down_revision = '1d18bf24593f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('blueprint_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'blueprints', ['blueprint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'blueprint_id')
    # ### end Alembic commands ###
